### ISSUE TITLE
Add suport for endpoint "timezones"

### ISSUE THREAD

**Issue by dilshan-weeraratne** [Adnuntius/api-tools#10]
Hi,

Please add support for the endpoint `/timezones`.

This will allow easy access without having to re-implement a HTTP request just to download the supported Timezones.

Thank you,
Dilshan

**Comment by jason-adnuntius** [comment]
yep can do that no issues

**Comment by dilshan-weeraratne** [comment]
Thank you.

**Comment by jason-adnuntius** [comment]
Done, sorry I missed this request.
